#!/bin/sh

cat <<EOF > Makefile
all:

install:
	mkdir -p ${DESTDIR}/usr/lib
	install os-release ${DESTDIR}/usr/lib
	mkdir -p ${DESTDIR}/usr/share/appdata
	mkdir -p ${DESTDIR}/etc
	install issue ${DESTDIR}/etc
	install issue.net ${DESTDIR}/etc
	install org.wpewebkit.Platform.appdata.xml ${DESTDIR}/usr/share/appdata
	install org.wpewebkit.Sdk.appdata.xml ${DESTDIR}/usr/share/appdata
	appstream-compose --basename=org.wpewebkit.Platform --prefix=/usr --origin=flatpak org.wpewebkit.Platform
	appstream-compose --basename=org.wpewebkit.Sdk --prefix=/usr --origin=flatpak org.wpewebkit.Sdk
EOF
