#!/bin/sh

cat <<EOF > Makefile
all:

install:
	mkdir -p ${DESTDIR}/usr/lib
	install os-release ${DESTDIR}/usr/lib
	mkdir -p ${DESTDIR}/usr/share/appdata
	mkdir -p ${DESTDIR}/etc
	install issue ${DESTDIR}/etc
	install issue.net ${DESTDIR}/etc
	install org.webkit.Platform.appdata.xml ${DESTDIR}/usr/share/appdata
	install org.webkit.Sdk.appdata.xml ${DESTDIR}/usr/share/appdata
	appstream-compose --basename=org.webkit.Platform --prefix=/usr --origin=flatpak org.webkit.Platform
	appstream-compose --basename=org.webkit.Sdk --prefix=/usr --origin=flatpak org.webkit.Sdk
EOF
